---

- name: Update OS
  apt:
    upgrade: "yes"
    update_cache: "yes"
    cache_valid_time: 86400

- name: Ensure correct kernel headers are installed
  apt:
    name:
      - "linux-headers-{{ ansible_kernel }}"
    state: present

# SSH daemon configuration.
- name: Configure SSH daemon.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^UseDNS'
      line: 'UseDNS no'
    - regexp: '^GSSAPIAuthentication'
      line: 'GSSAPIAuthentication no'

- name: Set Time Zone
  copy:
    content: "{{ time_zone }}\n"
    dest: "/etc/timezone"
    owner: root
    group: root
    mode: 0644
    backup: "yes"
  register: new_timezone

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: new_timezone is success

# VirtualBox tools installation.
- name: Check if VirtualBox is running the guest VM.
  shell: "dmesg | grep -i 'virtualization oracle' | wc -l"
  changed_when: false
  failed_when: false
  register: virtualbox_check

- include_tasks: virtualbox.yml
  when: virtualbox_check.stdout | int > 0

# Cleanup tasks.
- name: Remove unneeded packages.
  apt:
    name:
      - ppp
      - pppconfig
      - pppoeconf
      - cpp
      - gcc
      - g++
      - libx11-data
      - xauth
      - libxmuu1
      - libxcb1
      - libx11-6
      - libxext6
      - linux-source
      - '*-dev'
    state: absent

- name: Clean up apt
  apt:
    autoremove: "yes"
    autoclean: "yes"
