---

- name: Update OS
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Ensure correct kernel headers are installed
  apt:
    pkg: "linux-headers-{{ ansible_kernel }}"

# SSH daemon configuration.
- name: Configure SSH daemon.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^UseDNS'
      line: 'UseDNS no'
    - regexp: '^GSSAPIAuthentication'
      line: 'GSSAPIAuthentication no'

- name: Set Time Zone
  copy: content='{{ time_zone }}\n' dest=/etc/timezone owner=root group=root mode=0644 backup=yes
  register: new_timezone

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: new_timezone is success

# Cleanup tasks.
- name: Remove unneeded packages.
  apt:
    pkg:
      - ppp
      - pppconfig
      - pppoeconf
      - cpp
      - gcc
      - g++
      - libx11-data
      - xauth
      - libxmuu1
      - libxcb1
      - libx11-6
      - libxext6
      - linux-source
    state: absent

- name: Remove unneeded packages (by regex).
  shell: "apt-get -y remove '.*-dev$'"

- name: Clean up apt.
  command: "{{ item }}"
  changed_when: false
  with_items:
    - apt-get -y autoremove
    - apt-get -y clean
